import {
  researchAgent,
  estimationAgent,
  designAgent,
  validationAgent,
} from "./index";

export async function agentRouter(userQuery: string): Promise<{
  research: string;
  estimation: string;
  design: string;
  validation: string;
  summary: string;
}> {
  try {
    console.log("🔍 Starting Research Agent...");
    const researchResult = await researchAgent(userQuery);

    console.log("💰 Starting Estimation Agent...");
    const estimationResult = await estimationAgent(userQuery, researchResult);

    console.log("🎨 Starting Design Agent...");
    const designResult = await designAgent(userQuery, estimationResult);

    console.log("✅ Starting Validation Agent...");
    const validationResult = await validationAgent(
      estimationResult,
      designResult
    );

    // Create a professional summary
    const summary = `
📊 PROFESSIONAL CONSTRUCTION ESTIMATE REPORT

🔍 Market Research:
$${researchResult.substring(0, 300)}...

💰 Cost Estimation:
$${estimationResult.substring(0, 300)}...

🎨 Design Optimization:
$${designResult.substring(0, 300)}...

✅ Validation & Risk Assessment:
${validationResult.substring(0, 300)}...

---
Report generated by AI Fiesta Multi-Agent System
For detailed breakdown, please review each section above.
    `;

    return {
      research: researchResult,
      estimation: estimationResult,
      design: designResult,
      validation: validationResult,
      summary: summary,
    };
  } catch (error) {
    console.error("Agent Router Error:", error);
    throw new Error("Failed to process request through agent system");
  }
}
